export const actionTypes = {
  FETCH_CLIPS: 'FETCH_CLIPS',
  CLIP_SELECTED: 'CLIP_SELECTED',
  SUBMIT_CLIP: 'SUBMIT_CLIP',
  EDIT_CLIP: 'EDIT_CLIP',
  DELETE_CLIP: 'DELETE_CLIP',
  RAISE_ERROR: 'RAISE_ERROR'
};
